DROP DATABASE IF EXISTS hw1;
CREATE DATABASE hw1;
USE hw1;

CREATE TABLE  IF NOT EXISTS department
(
    DNUMBER      INT PRIMARY KEY,
    DNAME        VARCHAR(30) NOT NULL ,
    MGRSSN       CHAR(9),
    MGRSTARTDATE DATE
);

CREATE TABLE  IF NOT EXISTS dept_locations
(
    DNUMBER INT,
    DLOCATION VARCHAR(30) NOT NULL ,
    PRIMARY KEY (DNUMBER, DLOCATION),
    FOREIGN KEY (DNUMBER) REFERENCES department(DNUMBER)
);

CREATE TABLE  IF NOT EXISTS employee
(
    SSN     CHAR(9) PRIMARY KEY,
    FNAME   VARCHAR(15) NOT NULL,
    MINIT   CHAR(1) NOT NULL,
    LNAME   VARCHAR(15) NOT NULL,
    BDATE   DATE NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL,
    SEX    CHAR(1) NOT NULL,
    SALARY  DECIMAL(10, 2) NOT NULL,
    SUPERSSN CHAR(9),
    DNO      INT NOT NULL REFERENCES department(DNUMBER)
);

ALTER TABLE department ADD FOREIGN KEY (MGRSSN) REFERENCES employee(SSN);

CREATE TABLE  IF NOT EXISTS dependent
(
    ESSN     CHAR(9) NOT NULL ,
    DEPENDENT_NAME VARCHAR(15) NOT NULL ,
    SEX     CHAR(1) NOT NULL,
    BDATE    DATE NOT NULL,
    RELATIONSHIP VARCHAR(8) NOT NULL,
    PRIMARY KEY (ESSN, DEPENDENT_NAME),
    FOREIGN KEY (ESSN) REFERENCES employee(SSN)
);

CREATE TABLE  IF NOT EXISTS project
(
    PNUMBER INT PRIMARY KEY NOT NULL ,
    PNAME   VARCHAR(30) NOT NULL ,
    PLOCATION VARCHAR(30) NOT NULL ,
    DNUM    INT NOT NULL REFERENCES department(DNUMBER)
);


CREATE TABLE IF NOT EXISTS works_on
(
    ESSN    CHAR(9) NOT NULL ,
    PNO     INT NOT NULL ,
    HOURS   DECIMAL(3, 1) ,
    PRIMARY KEY (ESSN, PNO),
    FOREIGN KEY (ESSN) REFERENCES employee(SSN),
    FOREIGN KEY (PNO) REFERENCES project(PNUMBER)
);


















